# zap logger configuration
zap:
  level: 'info'
  #  format: 'console'
  #  format: 'console' # `json` or `console`
  format: 'json'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: false

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  db-type: 'mysql'
  oss-type: 'local'    # 控制oss选择走本期还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  use-multipoint: true
  addr: 7777

# mysql connect configuration
mysql:
  path: 127.0.0.1:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: test
  username: root
  password: "123456"
  max-idle-conns: 3
  max-open-conns: 3
  log-mode: true
  log-zap: ""


# grpc configuration
grpc:
  port: "1234"

jwt:
  signing-key: 'Bk7B5$F687DE88?67BFBC7@E863D#9*B'
  expires-time: 604800
  buffer-time: 86400

