// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//公共请求头
type CommonHeader struct {
	//trace_id
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	OperatorId           uint64   `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	OperatorType         uint32   `protobuf:"varint,3,opt,name=operator_type,json=operatorType,proto3" json:"operator_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonHeader) Reset()         { *m = CommonHeader{} }
func (m *CommonHeader) String() string { return proto.CompactTextString(m) }
func (*CommonHeader) ProtoMessage()    {}
func (*CommonHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *CommonHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonHeader.Unmarshal(m, b)
}
func (m *CommonHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonHeader.Marshal(b, m, deterministic)
}
func (m *CommonHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonHeader.Merge(m, src)
}
func (m *CommonHeader) XXX_Size() int {
	return xxx_messageInfo_CommonHeader.Size(m)
}
func (m *CommonHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonHeader.DiscardUnknown(m)
}

var xxx_messageInfo_CommonHeader proto.InternalMessageInfo

func (m *CommonHeader) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *CommonHeader) GetOperatorId() uint64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

func (m *CommonHeader) GetOperatorType() uint32 {
	if m != nil {
		return m.OperatorType
	}
	return 0
}

//公共响应状态
type BusinessStatus struct {
	//响应状态码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	//响应消息
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	//trace_id
	TraceId              string   `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusinessStatus) Reset()         { *m = BusinessStatus{} }
func (m *BusinessStatus) String() string { return proto.CompactTextString(m) }
func (*BusinessStatus) ProtoMessage()    {}
func (*BusinessStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *BusinessStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessStatus.Unmarshal(m, b)
}
func (m *BusinessStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessStatus.Marshal(b, m, deterministic)
}
func (m *BusinessStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessStatus.Merge(m, src)
}
func (m *BusinessStatus) XXX_Size() int {
	return xxx_messageInfo_BusinessStatus.Size(m)
}
func (m *BusinessStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessStatus.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessStatus proto.InternalMessageInfo

func (m *BusinessStatus) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BusinessStatus) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *BusinessStatus) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonHeader)(nil), "common.CommonHeader")
	proto.RegisterType((*BusinessStatus)(nil), "common.BusinessStatus")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x31, 0x4f, 0x85, 0x30,
	0x14, 0x85, 0x53, 0x41, 0x94, 0x2b, 0x18, 0xd3, 0x45, 0x98, 0x24, 0xb8, 0x30, 0xc9, 0xe0, 0xe8,
	0x86, 0x8b, 0x8c, 0x56, 0x27, 0x17, 0x53, 0xe8, 0xcd, 0x0b, 0x03, 0xdc, 0xa6, 0x2d, 0x2f, 0xe1,
	0xdf, 0xbf, 0x50, 0xc2, 0x4b, 0x98, 0xfa, 0x9d, 0xd3, 0x9b, 0x9c, 0x73, 0x20, 0xe9, 0x69, 0x1c,
	0x69, 0x7a, 0xd3, 0x86, 0x1c, 0xf1, 0x68, 0x53, 0x25, 0x41, 0xf2, 0xe9, 0xe9, 0x0b, 0xa5, 0x42,
	0xc3, 0x73, 0xb8, 0x77, 0x46, 0xf6, 0xf8, 0x3f, 0xa8, 0x8c, 0x15, 0xac, 0x8a, 0xc5, 0x9d, 0xd7,
	0xad, 0xe2, 0x2f, 0xf0, 0x40, 0x1a, 0x8d, 0x74, 0x64, 0xd6, 0xdf, 0x9b, 0x82, 0x55, 0xa1, 0x80,
	0xdd, 0x6a, 0x15, 0x7f, 0x85, 0xf4, 0x7a, 0xe0, 0x16, 0x8d, 0x59, 0x50, 0xb0, 0x2a, 0x15, 0xc9,
	0x6e, 0xfe, 0x2e, 0x1a, 0xcb, 0x6f, 0x78, 0x6c, 0x66, 0x3b, 0x4c, 0x68, 0xed, 0x8f, 0x93, 0x6e,
	0xb6, 0x9c, 0x43, 0xd8, 0x93, 0x42, 0x1f, 0x77, 0x2b, 0x3c, 0xf3, 0x27, 0x08, 0x46, 0x7b, 0xf2,
	0x19, 0xb1, 0x58, 0xf1, 0x50, 0x2c, 0x38, 0x14, 0x6b, 0xf2, 0xbf, 0x67, 0x8b, 0xe6, 0x8c, 0xa6,
	0xd6, 0x5d, 0xbd, 0xed, 0xfa, 0xd8, 0x9e, 0x2e, 0xf2, 0x6b, 0xdf, 0x2f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xcf, 0x5b, 0x7e, 0xf7, 0xfd, 0x00, 0x00, 0x00,
}
